apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhsm-subscriptions
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhsm-subscriptions
    app.kubernetes.io/part-of: rhsm-subscriptions
  name: rhsm-subscriptions
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rhsm-subscriptions
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rhsm-subscriptions
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-subs-watch-tenant/rhsm-subscriptions/rhsm-subscriptions@sha256:2195c5842f1774992fc8fdfae4408bbe7edfc2556dbb6b89aa42ea82a26fcf24
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 1Gi
status: {}
