apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhsm-subscriptions
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhsm-subscriptions
    app.kubernetes.io/part-of: rhsm-subscriptions
  name: rhsm-subscriptions
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: rhsm-subscriptions
status:
  loadBalancer: {}
