apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhsm-subscriptions
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-subs-watch-tenant/rhsm-subscriptions/rhsm-subscriptions@sha256:49b80ba1a8e60d8492b9bc92f8ef152d7b3dd9ca2b78e9e51d96717d4e2bfc86
        name: container-image
        resources: {}
status: {}
