apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhsm-subscriptions
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-subs-watch-tenant/rhsm-subscriptions/rhsm-subscriptions@sha256:ee0121c6ff705096df346f52deb2b062ef9d7c9a426df851838dff1a8b3d35a9
        name: container-image
        resources: {}
status: {}
