apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhsm-subscriptions
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-subs-watch-tenant/rhsm-subscriptions/rhsm-subscriptions@sha256:adfd7f0f7d6b285cf3c639c1523c28d5001cbffdcbc4fd5e4c1c38e3f52ccd00
        name: container-image
        resources: {}
status: {}
