apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhsm-subscriptions
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-subs-watch-tenant/rhsm-subscriptions/rhsm-subscriptions@sha256:f0124700b2c151f66ab0967a677abc91b2c5de769340b89d2d37d3d2bf3fb93b
        name: container-image
        resources: {}
status: {}
