apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhsm-subscriptions
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-subs-watch-tenant/rhsm-subscriptions/rhsm-subscriptions@sha256:082f2a2dde1139ede471cbdd84bfa277b9d6fe5baeadfc30555a82f1f807f0da
        name: container-image
        resources: {}
status: {}
