apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhsm-subscriptions
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-subs-watch-tenant/rhsm-subscriptions/rhsm-subscriptions@sha256:df51ba9fcdaa558cfb37ada3c7ec866337cea124afc57575b2dd70274fb8c7ce
        name: container-image
        resources: {}
status: {}
