apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhsm-subscriptions
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhsm-subscriptions
    app.kubernetes.io/part-of: rhsm-subscriptions
  name: rhsm-subscriptionsbkzj
spec:
  port:
    targetPort: 8000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rhsm-subscriptions
    weight: 100
status: {}
